### ISSUE TITLE
no zsh or smth

### ISSUE THREAD

**Issue by Yuzuru-Yamazaki** [Alopes01/Dotfiles#2]
`Failed to launch child:zsh 
with error: so such file or directory
`
I think it is because I have bash as default but I don't know .
I'm using i3 on linux mint 21.3 cinnamon

**Comment by Alopes01** [comment]
What programme were you testing?

**Comment by Yuzuru-Yamazaki** [comment]
kitty

**Comment by Alopes01** [comment]
Then it must be the shell, don't use the kitty config.  I think I only customised the fonts anyway. That cool prompt that you see with colours, autocomplition and icons can be achieved by the zsh. 
Because I was lazy there is actually a cool script I used that does everything for you. You just need a nerd font like Jetbrainsmono and zsh.

**Comment by Alopes01** [comment]
This is the script https://github.com/romkatv/zsh4humans

**Comment by Alopes01** [comment]
And if you are using bash I think the script will automatically change your default shell to zsh

**Comment by Yuzuru-Yamazaki** [comment]
I dropped that and just used the default terminal
