### ISSUE TITLE
same mint 

### ISSUE THREAD

**Issue by Yuzuru-Yamazaki** [Alopes01/Dotfiles#4]
error: /home/gun/.config/polybar/config:153: Unknown line type: <animation-charging> is used
idk what is wrong please help

**Comment by Alopes01** [comment]
Is the second rice as well?

**Comment by Alopes01** [comment]
Can you run 
```
polybar -c /home/gun/.config/polybar/config bar1
``` and send me the output .
Oh, and, change the name of the config to config.ini

**Comment by Alopes01** [comment]
I don't know how but somehow the config file got all commented there is no single line that it is active. I will fix it my self but in the mean time the fix is simple you just need to take out all of the semicolons ; in the beggining of each line . you can delete the credits or comment them.


Edit: I think it was the terminal kitty which commented all my lines because when you select paste and sanitize it comments all of the lines, anyways I'm sorry for the inconvenience

**Comment by Yuzuru-Yamazaki** [comment]
no problem and thanks
